Repository apache/skywalking-showcase, pull requests merged in 2022-04, with the labels that each got.

#24 Update the satellite image
  Makefile.in
Labels: dependencies

#28 Fix route to the satellite failure when using java-agent-injector in Kubernetes
  deploy/platform/kubernetes/Makefile
  deploy/platform/kubernetes/Makefile.in
  deploy/platform/kubernetes/features.mk
Labels: bug

#29 Add feature function
  deploy/platform/kubernetes/feature-function/resource.yaml
  deploy/platform/kubernetes/features.mk
  docs/readme.md
  services/function-load-gen/Dockerfile
  services/function-load-gen/Makefile
  services/function-load-gen/go.mod
  services/function-load-gen/go.sum
  services/function-load-gen/main.go
  services/function/Dockerfile
  services/function/Makefile
  services/function/go.mod
  services/function/go.sum
  services/function/main.go
Labels: enhancement
